name: Update YouTube Link

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update YouTube Videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWvl6LSoOfJ61WWu3EahFhA"
          max_post_count: 5
          comment_tag_name: "YOUTUBE"

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git status
          echo "your message here"
          git diff --quiet --exit-code || git commit -m "Update YouTube Videos"




